services:
  datalake:
    build: .
    container_name: aioc-datalake
    ports:
      - "8082:8082"
    volumes:
      - ./../../tests/containers/duckdb-datalake/TEST_DATA:/local-data
      - ./../../tests/containers/duckdb-datalake/test-db:/db-data
    networks:
      - datalake-network

networks:
  datalake-network:
    driver: bridge