storage:
  postgres:
    postgres_db:
      hostname:
        env: DAGSTER_PG_HOST
      username:
        env: DAGSTER_PG_USER
      password:
        env: DAGSTER_PG_PASSWORD
      db_name:
        env: DAGSTER_PG_DB
      port: 5432

compute_logs:
  module: dagster.core.storage.local_compute_log_manager
  class: LocalComputeLogManager
  config:
    base_dir: /app/compute_logs

run_launcher:
  module: dagster.core.launcher
  class: DefaultRunLauncher
